# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

## 테스트 계정 생성(어드민 권한 O)
test1 = User.create( email: 'kbs4674@naver.com', password: '123456', nickname: '어드민', admin: true )
user = User.find(1)
user.add_role :admin

## 테스트 계정 생성(어드민 권한 X)
test2 = User.create( email: 'test4674@naver.com', password: '123456', nickname: '테스트계정1',  admin: false )
user = User.find(2)
user.add_role :normal
user.add_role :block_yellow
user.add_role :block_red

test3 = User.create( email: 'test@naver.com', password: '123456', nickname: '테스트계정2',  admin: false )
test4 = User.create( email: 'test2@naver.com', password: '123456', nickname: '테스트계정3',  admin: false )
test5 = User.create( email: 'test3@naver.com', password: '123456', nickname: '테스트계정4',  admin: false )

## 게시판 생성
tip = Bulletin.create( title: '팁 게시판', content: '대학 꿀팁 게시판', opt_card_bulletin: true, opt_hashtag: true, user_nickname: '어드민', user_id: '1' )
free = Bulletin.create( title: '자유게시판', content: '자유게시판 입니다', user_nickname: '어드민', user_id: '1' )
argument = Bulletin.create( title: '건의사항', content: '건의사항 게시판 입니다', user_nickname: '어드민', user_id: '1' )

## 대학 혜택 정보
## 해시태그 약속 분류 : #기본제공 #공대 #컴퓨터공학 #디자이너 #미대 #일상樂 #먹방 #스터디 #학업 #장학금 #소프트웨어 #하드웨어 #할인 #우리만_있다 #무료 #취업
# Promotion.create( title: '', url: '', content: '', univ_hashtag: '')

Promotion.create( thumb: 'KOSAF', title: '한국장학재단', url: 'http://www.kosaf.go.kr/', content: '국가에서 지원해주는 장학금 사업으로, 소득에 따른 장학금 혜택 및 생활비/학자금을 최저 이자율로 대출해줍니다.', univ_hashtag: '#기본제공 #학업 #장학금')
Promotion.create( thumb: 'KOSAF', title: '파란 사다리', url: 'http://www.kosaf.go.kr/', content: '한국 장학재단에서 지원하는 파란 사다리 장학사업으로, 약 1개월간 진행되는 단기 어학연수 비용을 무료로 지원합니다.', univ_hashtag: '#학업 #장학금 #무료')
Promotion.create( thumb: 'ms', title: 'MS Office', url: 'https://products.office.com/ko-kr/student/office-in-education', content: 'MS의 모든 소프트웨어(Power Point, Excel, OneDrive 클라우드 1000GB) 등을 무료로 사용할 수 있게 합니다.', univ_hashtag: '#기본제공 #소프트웨어')
Promotion.create( thumb: 'naver_music', title: '네이버 뮤직', url: 'https://music.naver.com/buy/index.nhn?list=college', content: '1년에 한해 네이버 뮤직을 매 월 50% 할인된 가격으로 만나보실 수 있습니다.', univ_hashtag: '#기본제공 #일상樂 #할인')
Promotion.create( thumb: 'aws', title: 'AWS Credit 기본 제공', url: 'https://aws.amazon.com/ko/education/awseducate/', content: 'AWS Edu에 가입 시, AWS에서 사용할 수 있는 기본 크레딧을 제공해줍니다!', univ_hashtag: '#기본제공 #공대 #컴퓨터공학')
Promotion.create( thumb: 'aws', title: 'AWS Credit 100달러 제공', url: 'https://aws.amazon.com/ko/education/awseducate/', content: 'AWS Edu에 가입 시, AWS에서 사용할 수 있는 기본 크레딧을 제공해줍니다! 타 학교와는 다르게 100달러를 지원받으실 수 있습니다!', univ_hashtag: '#기본제공 #공대 #컴퓨터공학')
Promotion.create( thumb: 'github', title: 'Github', url: 'https://education.github.com/pack', content: '본인 및 본인이 지정한 사용자에게만 저장소를 열람할 수 있는 Private을 무료(Private 저장소 갯수는 무제한)로 지원해줍니다. 그 외에도 개발 툴(DATADOG, UNREAL Engine, ATOM 등) 쪽으로 혜택받은 정보를 아래 링크를 통해 확인할 수 있습니다!', univ_hashtag: '#기본제공 #공대 #컴퓨터공학 #무료')
Promotion.create( thumb: 'jet_brain', title: 'Jet Brain', url: 'https://www.jetbrains.com/', content: 'Visual Studio를 대체할 여러 개발 환경의 IDE이 학생 인증만 하면 무료로 제공됩니다!', univ_hashtag: '#기본제공 #공대 #컴퓨터공학 #소프트웨어 #무료')
Promotion.create( thumb: 'Y_Goon', title: 'YGOON 교육할인스토어', url: 'https://www.ygoon.com/mall/', content: '여행, 문화예술 활동, 전자기기 등 다양한 할인혜택을 받아보세요!', univ_hashtag: '#기본제공 #일상樂 #할인')
Promotion.create( thumb: 'job_planet', title: '잡 플래닛', url: 'https://www.jobplanet.co.kr/career_center/welcome/cover', content: '기업에 대한 평가/정보/면접후기를 광고시청 혹은 유료결제 없이 무제한적으로 열람하실 수 있습니다.', univ_hashtag: '#무료 #취업')
Promotion.create( thumb: 'win10', title: '윈도우 10', url: 'https://event.eventservice.co.kr/microsoft/2017/00/web/0223_win10.html', content: '윈도우10 정품 소프트웨어를 무료로 1회에 한해 정품 키 발급 및 소프트웨어를 다운로드 받으실 수 있습니다.', univ_hashtag: '#소프트웨어 #무료')
Promotion.create( thumb: 'inflearn', title: '인프런', url: 'https://www.inflearn.com/', content: 'IT 교육 플랫폼으로, 다양한 프로그래밍 언어를 온라인 수강을 통해 배워보실 수 있습니다. (인프런과 제휴를 맺은 대학은 3개까지의 온라인 강연이 무료로 제공됩니다.)', univ_hashtag: '#공대 #컴퓨터공학 #스터디 #학업')
Promotion.create( thumb: 'edwith', title: 'edwith', url: 'https://www.edwith.org/', content: 'NHN에서 운영하는 IT 교육 플랫폼으로, 다양한 프로그래밍 언어를 온라인 수강을 통해 배워보실 수 있습니다.', univ_hashtag: '#공대 #컴퓨터공학 #스터디 #학업')
Promotion.create( thumb: 'goorm', title: '구름 IDE', url: 'https://ide.goorm.io/', content: '클라우드 IDE로서, 다양한 개발 언어를 지원합니다. 각 대학별로 스터디 채널이 있어 같은 대학끼리 모여 온라인 스터디 진행이 가능합니다.', univ_hashtag: '#공대 #컴퓨터공학')
Promotion.create( thumb: 'KFC', title: 'KFC', url: 'http://delivery.kfckorea.com/', content: '오직 중앙대 학생들만 누릴 수 있는 할인혜택! KFC 매장에서 학생증을 제시하면 10% 할인이 됩니다!', univ_hashtag: '#먹방 #할인 #우리만_있다')
Promotion.create( thumb: 'Adobe', title: 'Adobe Creative Cloud', url: 'https://www.adobe.com/kr/creativecloud/buy/students.html', content: '어도비 클라우드(모든 Adobe 소프트웨어 시리즈)를 60% 할인을 받아보실 수 있습니다!', univ_hashtag: '#기본제공 #공대 #컴퓨터공학 #디자이너 #미대 #소프트웨어 #할인')
Promotion.create( thumb: 'apple', title: 'AOC', url: 'https://www.apple.com/kr/shop/browse/home/aoc', content: 'Apple에서 취급하는 제품들을 할인된 가격으로 만나보세요!', univ_hashtag: '#기본제공 #하드웨어 #할인')
Promotion.create( thumb: 'dbpia', title: '논문 열람 : DBPIA', url: 'http://dbpia.co.kr', content: '학교 도서관 사이트를 경유(지속적인 무료) 혹은 협약되어있는 대학 간 90일 동안 무료로 논문 열람이 가능합니다.', univ_hashtag: '#학업 #무료')
Promotion.create( thumb: 'RISS', title: '논문 열람 : RISS', url: 'http://www.riss.kr', content: '보통 학교 도서관 사이트에 가서 로그인 후, 사이트 내에 보이는 논문 사이트 링크를 통해 이동하시면 무료로 논문 열람이 가능합니다.', univ_hashtag: '#기본제공 #학업 #무료')
Promotion.create( thumb: 'MATLAB', title: 'Matlab', url: 'https://kr.mathworks.com/academia/student_version.html?s_tid=acport_sv_sp_cta1', content: '행렬을 기초로 한 수치 해석 및 프로그래밍 환경을 제공하는 공학용 소프트웨어입니다.', univ_hashtag: '#공대 #컴퓨터공학 #학업 #소프트웨어 #무료')
Promotion.create( thumb: 'autodesk', title: 'Auto Desk', url: 'https://www.autodesk.co.kr/education/free-educational-software', content: '오토캐드, 마야 등 오토데스크 브랜드에서 취급하는 3D 소프트웨어 입니다.', univ_hashtag: '#공대 #컴퓨터공학 #디자이너 #미대 #학업 #소프트웨어 #무료')
Promotion.create( thumb: 'dream_class', title: '삼성 드림클래스', url: 'https://www.dreamclass.org/index.do', content: '삼성에서 운영하는 복지사업 일환으로, 지원 대학생이 장학금을 받고 중학생들의 학업을 길러줍니다.', univ_hashtag: '#기본제공 #장학금')
Promotion.create( thumb: 'LH', title: 'LH 대학생 전세임대주택', url: 'https://apply.lh.or.kr/', content: '대학생 및 취업준비생들을 대상으로 시행하는 제도로, 주택 전세금을 지원해줍니다. (참고 : 지역마다 지원금액이 다릅니다.)', univ_hashtag: '#기본제공 #할인')
Promotion.create( thumb: 'Korail', title: '코레일 청소년드림', url: 'http://www.letskorail.com/', content: '만 24세 이하의 학생이라면 누구든 KTX를 최대 30% 할인을 받으실 수 있습니다.', univ_hashtag: '#기본제공 #할인')

## 대학 혜택 게시판
# Univ.create( univ_name_kor: '', univ_name_eng: '', img_name: "", email_url: "", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택, DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어") # 성결대

Univ.create( univ_name_kor: '가천대학교', univ_name_eng: 'Gachon University', img_name: "Gachon", email_url: "http://mail.gachon.ac.kr/index.ds", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어", aws_credit_100: true, aws_credit_normal: false) # 가천대
Univ.create( univ_name_kor: '강남대학교', univ_name_eng: 'Kangnam University', img_name: "Kangnam", email_url: "https://knusso.kangnam.ac.kr/login.jsp", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC)", AOC: true) # 강남대
Univ.create( univ_name_kor: '강원대학교', univ_name_eng: 'Kangwon National University', univ_nickname: "강대", img_name: "Kangwon", email_url: "http://mail.kangwon.ac.kr", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람, 윈도우 10(Window 10) Edu, 기타, 단기 어학장학 사업 : 파란사다리", blue_ladder: true, AOC: true, job_planet: true, win10: true, etc: true, aws_credit_100: true, aws_credit_normal: false ) # 강원대
Univ.create( univ_name_kor: '건국대학교', univ_name_eng: 'Konkuk University', img_name: "Konkuk", email_url: "http://mail.konkuk.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 윈도우 10(Window 10) Edu", win10: true, AOC: true, aws_credit_100: true, aws_credit_normal: false) # 건국대
Univ.create( univ_name_kor: '건양대학교', univ_name_eng: 'Konyang University', img_name: "Konyang", email_url: "http://mail.konyang.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어") # 건양대
Univ.create( univ_name_kor: '경기대학교', univ_name_eng: 'Kyonggi University', img_name: "Kyonggi", email_url: "http://mail.kyonggi.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 인프런(Inflearn) : IT 교육 플랫폼", inflearn: true, AOC: true) # 경기대
Univ.create( univ_name_kor: '경북대학교', univ_name_eng: 'Kyungpook National University', img_name: "Kyungpook", email_url: "http://mail.knu.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 윈도우 10(윈도우 10(Window 10) Edu, Ediwith : IT 교육플랫폼", edwith: true, win10: true, AOC: true) # 경북대
Univ.create( univ_name_kor: '경상대학교', univ_name_eng: 'Gyeongsang National University', img_name: "Gyeongsang", email_url: "https://webmail.gnu.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 윈도우 10(Window 10) Edu", win10: true, AOC: true) # 경상대
Univ.create( univ_name_kor: '경성대학교', univ_name_eng: 'Kyungsung University', img_name: "Kyungsung", email_url: "//apps.ks.ac.kr/ptl/sso/login.jsp", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어") # 경성대
Univ.create( univ_name_kor: '경희대학교', univ_name_eng: 'Kyunghee University', img_name: "Kyunghee", email_url: "https://mail.khu.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람, 윈도우 10(Window 10) Edu, 구름 IDE : 클라우드 IDE", aws_credit_100: true, aws_credit_normal: false, goorm_ide: true, win10: true, job_planet: true, AOC: true) # 경희대
Univ.create( univ_name_kor: '계명대학교', univ_name_eng: 'Keimyung University', img_name: "Keimyung", email_url: "http://webmail.kmu.ac.kr", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어") # 계명대
Univ.create( univ_name_kor: '고려대학교', univ_name_eng: 'Korea University', univ_nickname: "고대", img_name: "Korea", email_url: "https://mail.korea.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람", aws_credit_100: true, aws_credit_normal: false, job_planet: true, AOC: true) # 고려대
Univ.create( univ_name_kor: '광운대학교', univ_name_eng: 'Kwangwoon University', img_name: "Kwangwoon", email_url: "https://wmail.kw.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC)", AOC: true) # 광운대
Univ.create( univ_name_kor: '국민대학교', univ_name_eng: 'Kookmin University', img_name: "Kookmin", email_url: "https://apps.kookmin.ac.kr/login/loginForm.do", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람", aws_credit_100: true, aws_credit_normal: false, job_planet: true, AOC: true) # 국민대
Univ.create( univ_name_kor: '남서울대학교', univ_name_eng: 'Namseoul University', img_name: "Namseoul", email_url: "웹메일 제공 없음.", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어") # 남서울대
Univ.create( univ_name_kor: '단국대학교', univ_name_eng: 'Dankook University', img_name: "Dankook", email_url: "http://outlook.com/dankook.ac.kr", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람", job_planet: true, AOC: true) # 단국대
Univ.create( univ_name_kor: '대구경북과학기술원', univ_name_eng: 'Daegu Gyeongbuk Institute of Science and Technology (DGIST)', univ_nickname: "DGIST 디지스트 경과기", img_name: "DIGIST", email_url: "https://mail.dgist.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 윈도우 10(Window 10) Edu", win10: true) # 대구경북과학기술원(DIGIST)
Univ.create( univ_name_kor: '덕성여자대학교', univ_name_eng: "Duksung Women's University", univ_nickname: "덕성여대", img_name: "Duksung", email_url: "https://mail.duksung.ac.kr/account/login.do", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람", job_planet: true, AOC: true) # 덕성여대
Univ.create( univ_name_kor: '동국대학교', univ_name_eng: 'Dongguk University', img_name: "Dongguk", email_url: "https://mail.dongguk.edu/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 윈도우 10(Window 10) Edu", aws_credit_100: true, aws_credit_normal: false, win10: true, AOC: true) # 동국대
Univ.create( univ_name_kor: '동덕여자대학교', univ_name_eng: "Dongduk Women's University", univ_nickname: "동덕여대", img_name: "Dongduk", email_url: "http://email.dongduk.ac.kr", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람", job_planet: true, AOC: true) # 동덕여대
Univ.create( univ_name_kor: '명지대학교', univ_name_eng: 'Myongji University', img_name: "Myongji", email_url: "http://sso.mju.ac.kr/swift/login/login_mail.jsp", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC)", aws_credit_100: true, aws_credit_normal: false, AOC: true) # 명지대
Univ.create( univ_name_kor: '목포대학교', univ_name_eng: 'Mokpo National University', img_name: "Mokpo", email_url: "https://mnuwb.mokpo.ac.kr/http://mail.mokpo.ac.kr/index.jsp", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어") # 목포대
Univ.create( univ_name_kor: '부산대학교', univ_name_eng: 'Pusan National University', img_name: "Pusan", email_url: "https://webmail.pusan.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 윈도우 10(Window 10) Edu", aws_credit_100: true, aws_credit_normal: false, win10: true, AOC: true) # 부산대
Univ.create( univ_name_kor: '삼육대학교', univ_name_eng: 'Sahmyook University', img_name: "Sahmyook", email_url: "정보전산원 문의(02-3399-3207)", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람", job_planet: true, AOC: true) # 삼육대
Univ.create( univ_name_kor: '상명대학교', univ_name_eng: 'Sangmyung University', img_name: "Sangmyung", email_url: "http://sso.smu.ac.kr 로그인 후, Office 365을 통해 가입", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람", job_planet: true, AOC: true) # 상명대
Univ.create( univ_name_kor: '서강대학교', univ_name_eng: 'Sogang University', img_name: "Sogang", email_url: "https://mail.sogang.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람, 윈도우 10(Window 10) Edu, Ediwith : IT 교육플랫폼", aws_credit_100: true, aws_credit_normal: false, edwith: true, win10: true, job_planet: true, AOC: true) # 서강대
Univ.create( univ_name_kor: '서울과학기술대학교', univ_name_eng: 'Seoul National University of Science and Technology', univ_nickname: "서과기", img_name: "SEOULTECH", email_url: "http://mail.seoultech.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람", job_planet: true, AOC: true) # 서울과학기술대
Univ.create( univ_name_kor: '서울대학교', univ_name_eng: 'Seoul National University', img_name: "Seoul", email_url: "https://mail.snu.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 윈도우 10(Window 10) Edu", aws_credit_100: true, aws_credit_normal: false, win10: true) # 서울대
Univ.create( univ_name_kor: '서울시립대학교', univ_name_eng: 'University of Seoul', univ_nickname: "서시대", img_name: "UOS", email_url: "https://mail.uos.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람", job_planet: true, AOC: true) # 서울시립대
Univ.create( univ_name_kor: '서울여자대학교', univ_name_eng: "Seoul Women's University", univ_nickname: "서울여대", img_name: "Seoul_Women", email_url: "https://mail.swu.ac.kr/member/login?t=1541607909", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC)", AOC: true) # 서울여대
Univ.create( univ_name_kor: '선문대학교', univ_name_eng: 'SunMoon University', img_name: "SunMoon", email_url: "http://mail.sunmoon.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어", aws_credit_100: true, aws_credit_normal: false) # 선문대
Univ.create( univ_name_kor: '성결대학교', univ_name_eng: 'Sungkyul University', img_name: "Sungkyul", email_url: "https://mail.sungkyul.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어") # 성결대
Univ.create( univ_name_kor: '성공회대학교', univ_name_eng: 'SungKongHoe University', img_name: "SungKongHoe", email_url: "http://outlook.com/skhu.kr", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어") # 성공회대
Univ.create( univ_name_kor: '성균관대학교', univ_name_eng: 'Sungkyunkwan University', img_name: "Sungkyunkwan", email_url: "https://mail.skku.edu", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람, 윈도우 10(Window 10) Edu", win10: true, job_planet: true, AOC: true) # 성균관대
Univ.create( univ_name_kor: '성신여자대학교', univ_name_eng: "Sungshin Women's University", univ_nickname: "성신여대", img_name: "Sungshin_Women", email_url: "https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ltmpl=default&hd=sungshin.ac.kr&service=mail&sacu=1&rip=1", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC)", AOC: true) # 성신여대
Univ.create( univ_name_kor: '세종대학교', univ_name_eng: 'Sejong University', img_name: "Sejong", email_url: "http://portal.office.com/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC)", AOC: true) # 세종대
Univ.create( univ_name_kor: '숙명여자대학교', univ_name_eng: "Sookmyung Women's University", univ_nickname: "숙명여대", img_name: "Sookmyung_Women", email_url: "https://sites.google.com/sookmyung.ac.kr/gsuite", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC)", aws_credit_100: true, aws_credit_normal: false, AOC: true) # 숙명여대
Univ.create( univ_name_kor: '아주대학교', univ_name_eng: 'Ajou University', img_name: "Ajou", email_url: "G-Suite 메일 사용", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람, 단기 어학장학 사업 : 파란사다리", blue_ladder: true, aws_credit_100: true, aws_credit_normal: false, job_planet: true, AOC: true) # 아주대
Univ.create( univ_name_kor: '연세대학교', univ_name_eng: 'Yonsei University', univ_nickname: "연대", img_name: "Yonsei", email_url: "https://mail.yonsei.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람, 윈도우 10(Window 10) Edu", aws_credit_100: true, aws_credit_normal: false, win10: true, job_planet: true, AOC: true) # 연세대
Univ.create( univ_name_kor: '영남대학교', univ_name_eng: 'Yeungnam University', img_name: "Yeungnam", email_url: "https://office.yu.ac.kr/Asp2/Default.aspx", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC)", AOC: true) # 영남대
Univ.create( univ_name_kor: '용인대학교', univ_name_eng: 'Yongin University', img_name: "Yongin", email_url: "http://www.yongin.ac.kr/guides/itservice/email", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어") # 용인대
Univ.create( univ_name_kor: '울산과학기술원', univ_name_eng: 'Ulsan National Institute of Science and Technology (UNIST)', univ_nickname: "UNIST 유니스트 울과기", img_name: "UNIST", email_url: "https://mail.unist.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람, 윈도우 10(Window 10) Edu", win10: true, job_planet: true, AOC: true) # 울산과학기술원 (UNIST)
Univ.create( univ_name_kor: '울산대학교', univ_name_eng: 'Ulsan University', img_name: "Ulsan", email_url: "https://mail.ulsan.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 윈도우 10(Window 10) Edu", win10: true, AOC: true) # 울산대
Univ.create( univ_name_kor: '원광대학교', univ_name_eng: 'Wonkwang University', img_name: "Wonkwang", email_url: "https://cc.wku.ac.kr/?p=1092", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어") # 원광대
Univ.create( univ_name_kor: '이화여자대학교', univ_name_eng: "Ewha Womans University", univ_nickname: "이화여대", img_name: "Ewha_Womans", email_url: "https://www.ewha.ac.kr/mbs/ewhakr/subview.jsp?id=ewhakr_060401040300", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 잡플래닛 무료열람, 윈도우 10(Window 10) Edu", win10: true, job_planet: true) # 이화여대
Univ.create( univ_name_kor: '인천대학교', univ_name_eng: 'Incheon National University', img_name: "Incheon", email_url: "https://webmail.inu.ac.kr", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 잡플래닛 무료열람", aws_credit_100: true, aws_credit_normal: false, job_planet: true, AOC: true) # 인천대
Univ.create( univ_name_kor: '인하대학교', univ_name_eng: 'Inha University', img_name: "Inha", email_url: "https://mail.inha.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 윈도우 10(Window 10) Edu", aws_credit_100: true, aws_credit_normal: false, win10: true, AOC: true) # 인하대
Univ.create( univ_name_kor: '전북대학교', univ_name_eng: 'Chonbuk National University', img_name: "Chonbuk", email_url: "https://cbnu.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 윈도우 10(Window 10) Edu, 단기 어학장학 사업 : 파란사다리", blue_ladder: true, aws_credit_100: true, aws_credit_normal: false, win10: true) # 전북대
Univ.create( univ_name_kor: '조선대학교', univ_name_eng: 'Chosun University', univ_nickname: "조대", img_name: "Chosun", email_url: "http://www.chosun.ac.kr/user/indexSub.do?codyMenuSeq=31849651&siteId=itc", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어") # 조선대
Univ.create( univ_name_kor: '중앙대학교', univ_name_eng: 'Chung-Ang University', img_name: "Chung-Ang", email_url: "http://portal.cau.ac.kr/_Layouts/help/cau_portal_menual_04.html", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, KFC, 애플 스토어 할인(AOC), 윈도우 10(Window 10) Edu", aws_credit_100: true, aws_credit_normal: false, win10: true, AOC: true, KFC: true) # 중앙대
Univ.create( univ_name_kor: '충남대학교', univ_name_eng: 'Chungnam National University', img_name: "Chungnam", email_url: "http://cuvic.cnu.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 윈도우 10(Window 10) Edu, 인프런(Inflearn) : IT 교육 플랫폼, 단기 어학장학 사업 : 파란사다리, 잡플래닛 무료열람", blue_ladder: true, aws_credit_100: true, aws_credit_normal: false, inflearn: true, win10: true, AOC: true, job_planet: true) # 충남대
Univ.create( univ_name_kor: '충북대학교', univ_name_eng: 'Chungbuk University', img_name: "Chungbuk", email_url: "http://chungbuk.ac.kr", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 윈도우 10(Window 10) Edu", win10: true) # 충북대
Univ.create( univ_name_kor: '평택대학교', univ_name_eng: 'Pyeongtaek University', img_name: "Pyeongtaek", email_url: "https://mail.ptu.ac.kr", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어") # 평택대
Univ.create( univ_name_kor: '한경대학교', univ_name_eng: 'Hankyong National University', img_name: "Hankyong", email_url: "http://mail.hknu.ac.kr/", content: "한국장학재단 : 국가장학금, 단기 어학장학 사업 : 파란사다리, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택, DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어", blue_ladder: true) # 한경대
Univ.create( univ_name_kor: '한국기술교육대학교', univ_name_eng: 'Korea University of Technology and Education (KOREATECH)', univ_nickname: "KOREATECH 코리아텍 코리아택", img_name: "KOREATECH", email_url: "http://email.koreatech.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 잡플래닛 무료열람", job_planet: true) # 한국기술교육대 (KOREATECH)
Univ.create( univ_name_kor: '한국산업기술대학교', univ_name_eng: 'Korea Polytechnic University', univ_nickname: "한산기", img_name: "Korea_Polytechnic", email_url: "http://blog.naver.com/kpu_iphak/220956393721", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어", aws_credit_100: true, aws_credit_normal: false) # 한국산업기술대
Univ.create( univ_name_kor: '한국외국어대학교', univ_name_eng: 'Foreign Language College of Korea', univ_nickname: "한국외대", img_name: "Foreign_Language", email_url: "http://webmail.hufs.ac.kr", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 윈도우 10(Window 10) Edu, 구름 IDE : 클라우드 IDE", goorm_ide: true, win10: true, AOC: true) # 한국외대
Univ.create( univ_name_kor: '한국항공대학교', univ_name_eng: 'Korea Aerospace University', univ_nickname: "항공대", img_name: "Korea_Aerospace", email_url: "http://mail.kau.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC)", AOC: true) # 한국항공대
Univ.create( univ_name_kor: '한밭대학교', univ_name_eng: 'Hanbat National University', img_name: "Hanbat", email_url: "https://mail.hanbat.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어") # 한밭대
Univ.create( univ_name_kor: '한양대학교', univ_name_eng: 'Hanyang University', univ_nickname: "한대", img_name: "Hanyang", email_url: "https://mail.hanyang.ac.kr/", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS 100달러 Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC), 윈도우 10(Window 10) Edu", aws_credit_100: true, aws_credit_normal: false, win10: true, AOC: true) # 한양대
Univ.create( univ_name_kor: '홍익대학교', univ_name_eng: 'Hongik University', univ_nickname: "홍대", img_name: "Hongik", email_url: "https://hmail.hongik.ac.kr/owa", content: "한국장학재단 : 국가장학금, Adobe 소프트웨어 패키지, 매트랩, 오토데스크 소프트웨어, 삼성 드림클래스, 코레일 청소년드림, LH 대학생 전세임대주택 DBPIA, RISS, MS Office, 네이버 뮤직 1년 할인, AWS Credit, Github, Jet Brain, YGOON 대학생 복지몰 교육할인스토어, 애플 스토어 할인(AOC)", AOC: true) # 홍익대

## 데이터 테스트용
# for num in 1..50000
#     AllNotice.create( title: "#{num}", content: "안녕#{num+2}", global_notice: 'false', local_notice: 'false', user_nickname: "어드민", user_id: "1" )
# end